---
title: 'Multi-HiC QC report'
date: "`r date()`"
user: 'HiCool'
output:
    rmdformats::readthedown:
        highlight: tango
        toc: 3
        self-contained: true
        embed-resources: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, return = FALSE, output = FALSE, message = FALSE}
## -- Load required libraries
require(HiCExperiment)
require(HiCool)

## -- Parse data 
log_files <- "%LOGS%" |> 
    strsplit(',') |> 
    unlist()
names(log_files) <- gsub('\\^.*', '', basename(log_files))
file_cools <- lapply(log_files, function(x) {
    f <- gsub(".log$", ".mcool", gsub("logs", "matrices", x))
    if (!file.exists(f)) {
        message(paste0(x, ': associated cool file not found.'))
        return("")
    }
    else {
        return(f)
    }
})
file_pairs <- lapply(log_files, function(x) {
    f <- gsub(".log$", ".pairs", gsub("logs", "pairs", x))
    if (!file.exists(f)) {
        message(paste0(x, ': associated pairs file not found.'))
        return("")
    }
    else {
        return(f)
    }
})
stats <- lapply(log_files, HiCool::getHicStats) |> 
    dplyr::bind_rows(.id = 'sample') |> 
    dplyr::mutate(sample = factor(sample, make.unique(names(log_files))))
```

## Samples

```{r, comment = ""}
if (all(file_cools != "")) {
    cfs <- lapply(seq_along(log_files), function(i) {
        HiCExperiment::CoolFile(
            file_cools[[i]], 
            pairs = file_pairs[[i]], 
            metadata = list(
                log = log_files[[i]], 
                args = getHiCoolArgs(log_files[[i]]), 
                stats = getHicStats(log_files[[i]])
            )
        )
    })
    names(cfs) <- gsub('\\^.*', '', basename(log_files))
    cfs
} else {
    message("Only log files are available:")
    writeLines(paste0('$ ', log_files))
}
```

<hr>

## Mapping results

```{r}
stats
```

```{r}
df <- dplyr::select(stats, sample, nFragments, nPairs, nFiltered, nUnique) |> 
    dplyr::rename(
        `All fragments` = nFragments, 
        `Mapped pairs` = nPairs, 
        `Filtered pairs` = nFiltered,
        `Unique pairs` = nUnique
    ) |>
    tidyr::pivot_longer(-c(sample), names_to = 'val', values_to = 'number') |>
    dplyr::mutate(val = factor(val, 
        c("All fragments", "Mapped pairs", "Filtered pairs", "Unique pairs"))
    )
fig1 <- plotly::plot_ly(
    df, 
    x = ~sample, 
    y = ~number, 
    color = ~val,
    type = 'bar',
    hoverinfo = ~number,
    showlegend = TRUE
) |> 
    plotly::layout(
        yaxis = list(title = 'Total # of fragments'), 
        xaxis = list(title = ''), 
        legend = list(orientation = 'h')
    )
fig1
```

</br>
</br>

```{r}
df <- stats |> 
    dplyr::rowwise() |> 
    dplyr::mutate(
        nUnmapped = nFragments-nPairs
    ) |> 
    dplyr::select(sample, nUnique, nDups, nDangling, nSelf, nDumped, nUnmapped) |> 
    dplyr::rename(
        `Unique filtered pairs` = nUnique, 
        `Duplicated pairs` = nDups, 
        `Dangling fragments ('uncut')` = nDangling, 
        `Self-religated fragments ('loops')` = nSelf, 
        `Invalid pairs ('dumped')` = nDumped,
        `Unmapped pairs` = nUnmapped,
    ) |>
    tidyr::pivot_longer(-c(sample), names_to = 'val', values_to = 'number') |>
    dplyr::mutate(val = factor(val, c(
        "Unique filtered pairs", 
        "Duplicated pairs", 
        "Dangling fragments ('uncut')", 
        "Self-religated fragments ('loops')", 
        "Invalid pairs ('dumped')", 
        "Unmapped pairs"
    ))) |> 
    dplyr::group_by(sample) |> 
    dplyr::mutate(pct = number / sum(number) * 100)
fig2 <- plotly::plot_ly(
    df, 
    y = ~sample, 
    x = ~pct, 
    color = ~val,
    type = 'bar',
    orientation = 'h', 
    hoverinfo = ~number,
    showlegend = TRUE
) |> 
    plotly::layout(
        yaxis = list(title = 'Sample'), 
        xaxis = list(
            title = '% of sequenced fragments',
            side = 'top'
        ),
        barmode = 'stack', 
        legend = list(
            orientation = 'h'
        )
    )
fig2
```

## Hi-C quality control


## Session information

> System

```{r}
message(
    "OS:\t\t\t\t", sessioninfo::os_name(), '\n',
    "system:\t\t\t", version$system, '\n',
    "UI:\t\t\t\t", .Platform$GUI, '\n',
    "R:\t\t\t\t", paste(
        version$major, version$minor, sep = '.'
    ), "(", R.home(), ")", '\n',
    "Python:\t\t\t", basilisk::listPythonVersion(HiCool:::env_HiCool), "(", file.path(
        basilisk::obtainEnvironmentPath(HiCool:::env_HiCool), 'bin', 'python'
    ), ")", '\n',
    "Bioconductor:\t", BiocManager::version(), '\n',
    "basilisk:\t\t", packageVersion('basilisk'), '\n',
    "HiCExperiment:\t", packageVersion('HiCExperiment'), '\n',
    "HiCool:\t\t\t", packageVersion('HiCool'), '\n'
)
```

> System packages

```{r}
message(
    "samtools: \t", gsub('.*==', '', grep('samtools', HiCool:::.HiCool_dependencies, value = TRUE)), "\n",
    "bowtie2: \t", gsub('.*==', '', grep('bowtie2', HiCool:::.HiCool_dependencies, value = TRUE)), "\n"
)
```

> R packages 

```{r}
sessioninfo::package_info()
```

> Python environment

```{r}
proc <- basilisk::basiliskStart(HiCool:::env_HiCool)
sessioninfo::python_info()
basilisk::basiliskStop(proc)
```

> Python packages

```{r}
basilisk::listPackages(HiCool:::env_HiCool)
```
