#' @title HiC processing report
#' 
#' @name HiCReport
#' @rdname HiCReport
#' 
#' @param x an CoolFile object, generated from `HiCool::HiCool()` or 
#'   `HiCool::importHiCoolFolder()`, or directly from calling 
#'   `HiCExperiment::CoolFile()`.
#' @param output Path to save output HTML file.
#' @param hash Hashes to use to search for log and cool files 
#'   generated by hicstuff/HiCool
#' @param logs Log files from hicstuff/HiCool
#' @param directory Where to look for log files?
#'
#' @importFrom rmarkdown render
#' @importFrom rmdformats readthedown
#' @importFrom plotly plot_ly
#' @importFrom plotly layout
#' @importFrom sessioninfo os_name
#' @importFrom sessioninfo package_info
#' @importFrom sessioninfo python_info
#' @importFrom BiocIO resource
#' @importFrom S4Vectors metadata
#' @export
#' @examples 
#' mcool_path <- HiContactsData::HiContactsData('yeast_wt', 'mcool')
#' pairs_path <- HiContactsData::HiContactsData('yeast_wt', 'pairs.gz')
#' log_path <- HiContactsData::HiContactsData(sample = 'yeast_wt', format = 'HiCool_log')
#' cf <- CoolFile(mcool_path, pairs = pairs_path, metadata = list(log = log_path))
#' HiCReport(cf)
#' HiCReports(logs = c(log_path))

HiCReport <- function(x, output = NULL) {

    ## --- Parse CoolFile for info
    mcool <- normalizePath(BiocIO::resource(x))
    pairs <- normalizePath(pairsFile(x))
    log_file <- normalizePath(S4Vectors::metadata(x)$log)

    ## --- Check that all required fields exist
    if (!length(mcool))
        stop("No cool file was found.")
    if (!length(pairs))
        message("Warning: No pairs file was found.")
    if (!file.exists(mcool))
        stop("The associated cool file is missing.")
    if (!file.exists(pairs))
        message("Warning: The associated pairs file is missing.")
    if (is.null(log_file))
        stop("Missing log file.")
    if (!file.exists(log_file))
        stop("Log file does not exist.")
    
    ## --- Prepare output files
    if (is.null(output)) {
        output <- file.path(
            dirname(dirname(mcool)), 
            gsub('\\..?cool', '.html', basename(mcool))
        )
        if (!grepl('.html', output))
            output <- paste0(output, '.html')
    }

    ## --- Generate report
    tmpdir <- tempdir()
    tmpRmd <- file.path(tmpdir, basename(gsub('.html$', '.Rmd', output)))
    tmpHtml <- file.path(tmpdir, basename(output))
    unlink(tmpRmd)
    unlink(tmpHtml)
    unlink(output)
    file.copy(
        system.file('templates', 'HiCoolFile_report_template.Rmd', package = 'HiCool'), 
        tmpRmd
    )
    writeLines(gsub("%COOL%", mcool, readLines(tmpRmd)), tmpRmd)
    writeLines(gsub("%PAIRS%", pairs, readLines(tmpRmd)), tmpRmd)
    writeLines(gsub("%LOG%", log_file, readLines(tmpRmd)), tmpRmd)
    rmarkdown::render(tmpRmd, quiet = TRUE)
    writeLines(gsub("&amp;quot;", '"', readLines(tmpHtml)), tmpHtml)
    file.copy(tmpHtml, output)
    unlink(tmpRmd)
    unlink(tmpHtml)
    message("HiCool :: Report generated and available @ ", output)
    TRUE
}

#' @rdname HiCReport
#' @export

HiCReports <- function(hash, directory = '.', logs = NULL, output = NULL) {

    ## --- Parse CoolFiles 
    if (is.null(logs)) {
        logs <- lapply(hash, function(x) {
            list.files(path = directory, pattern = paste0(x, '.log'), recursive = TRUE, full.names = TRUE)
        }) |> unlist()
    }
    log_files <- paste(logs, collapse = ',')
    
    ## --- Prepare output files
    if (is.null(output)) {
        output <- 'HiCReports.html'
    }

    ## --- Generate report
    tmpdir <- tempdir()
    tmpRmd <- file.path(tmpdir, basename(gsub('.html$', '.Rmd', output)))
    tmpHtml <- file.path(tmpdir, basename(output))
    unlink(tmpRmd)
    unlink(tmpHtml)
    unlink(output)
    file.copy(
        system.file('templates', 'HiCoolFile_reports_template.Rmd', package = 'HiCool'), 
        tmpRmd
    )
    writeLines(gsub("%LOGS%", log_files, readLines(tmpRmd)), tmpRmd)
    rmarkdown::render(tmpRmd, quiet = TRUE)
    writeLines(gsub("&amp;quot;", '"', readLines(tmpHtml)), tmpHtml)
    file.copy(tmpHtml, output)
    unlink(tmpRmd)
    unlink(tmpHtml)
    message("Report generated and available @ ", output)
    TRUE
}
